name: "setup-pdm-env"
description: "Composite action to setup the Python and PDM environment."

inputs:
   python-version:
     required: false
     description: "The python version to use"
     default: "3.11"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      # You are now able to use PDM in your workflow
      with:
        cache: true
        update-python: true
        python-version: ${{ inputs.python-version }}
    - name: Generate lock file
      run: pdm lock
      shell: bash
    - name: Install dependencies
      run: pdm install
      shell: bash
